### ISSUE TITLE
msg: rmtree failed: [Errno 39] Directory not empty: '/var/lib/tomcat7/webapps/biocache-service/WEB-INF/lib'

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/ala-install#60]
Seeing this error on redeploys

```
failed: [ala-demo] => {"failed": true}
msg: rmtree failed: [Errno 39] Directory not empty: '/var/lib/tomcat7/webapps/biocache-service/WEB-INF/lib'

FATAL: all hosts have already failed -- aborting
```

Im not sure if the correct thing is to remove the old war and expanded directory each time or not.

**Comment by djtfmartin** [comment]
@m-r-c any thoughts on this one ?

**Comment by m-r-c** [comment]
It was caused by a race between tomcat deploying the new WAR file, and the script trying to delete the old exploded directories. I have swapped the order of the tasks so the directory is deleted before the download. It means a full redeploy each time the script is run, whereas previously it only deleted the directories if the WAR file had changed, but that doesn't matter.

**Comment by djtfmartin** [comment]
thanks @m-r-c, that all makes sense.
