### ISSUE TITLE
Couldn't resolve module/action 'community.postgresql.postgresql_membership'

### ISSUE THREAD

**Issue by vjrj** [AtlasOfLivingAustralia/ala-install#712]
There is an issue introduced by [this commit](https://github.com/AtlasOfLivingAustralia/ala-install/commit/5cad2a08091ec37dcd59b4426eace5dbb06add06#diff-af1170bbb46653e12c266dbeef940bfd4e6c6b9dbabd5afdbe7761dae297fac4).

![image](https://github.com/AtlasOfLivingAustralia/ala-install/assets/180085/2293c918-aa3c-4567-802b-45e0384f79de)

We need to install an extra module?

cc @matthewandrews .

**Comment by matthewandrews** [comment]
That's curious.  The community.postgresql collection has been needed by other modules like postgresql_db and postgresql_user for a long time, I think.  Maybe because the module path is fully qualified?  Does it work if you change the task from "community.postgresql.postgresql_membership" to "postgresql_membership"?

**Comment by vjrj** [comment]
Yes, you are right.

**Comment by matthewandrews** [comment]
Thanks for testing- I've merged your fix PR now.
